const ActionTypes ={
UPDATE_USER : 'UPDATE_USER ',
UPDATE_USER_RESPONSE : 'UPDATE_USER_RESPONSE',
REQ_GET_USER : 'REQ_GET_USER',
GET_USER_RESPONSE : 'GET_USER_RESPONSE',
ADD_USER : 'ADD_USER',
ADD_USER_RESPONSE :'ADD_USER_RESPONSE',
DEL_USER : 'DEL_USER',
DEL_USER_RESPONSE : 'DEL_USER_RESPONSE',

//product
UPDATE_PRODUCT : 'UPDATE_PRODUCT ',
UPDATE_PRODUCT_RESPONSE : 'UPDATE_PRODUCT_RESPONSE',
REQ_GET_PRODUCT : 'REQ_GET_PRODUCT',
GET_PRODUCT_RESPONSE : 'GET_PRODUCT_RESPONSE',
ADD_PRODUCT : 'ADD_PRODUCT',
ADD_PRODUCT_RESPONSE :'ADD_PRODUCT_RESPONSE',
DEL_PRODUCT : 'DEL_USER',
DEL_PRODUCT_RESPONSE : 'DEL_PRODUCT_RESPONSE',

//login
LOGIN : 'LOGIN',
LOGIN_RESPONSE : 'LOGIN_RESPONSE',

//pagnation
PAG : 'PAG',
PAG_RESPONSE : 'PAG_RESPONSE',
};
export default ActionTypes